baseURL = "https://internal-red-tape-reduction-report.github.io/"
languageCode = "en-us"
title = "Internal Red Tape Reduction Report"
googleAnalytics = "UA-164662709-1"

[params]
  author = "Blueprint 2020 Internal Red Tape Reduction Tiger Team"
  description = "During the Blueprint 2020 discussions, public servants reported that many rules and processes were overly complex, top-down and lacked coherence. Simplifying internal processes and reducing internal red tape was identified as one of the five priority areas of action. This report presents key findings and recommendations that reflect the voices of public servants. Released under the Access to Information Act."

[sitemap]
    changefreq = "weekly"
    priority = 0.5

[permalinks]
  posts = "/:year/:month/:day/:slug/"
  pages = "/:slug/"

[blackfriday]
  fractions = false

[markup]
  defaultMarkdownHandler = "goldmark"

  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 3
